name: sceneweaver
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.15
      - albumentations==1.4.14
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cssutils==2.11.1
      - cycler==0.12.1
      - cython==3.0.11
      - dill==0.4.0
      - distro==1.9.0
      - einops==0.8.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - filelock==3.16.0
      - fonttools==4.57.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.66.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - idna==3.8
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - inflect==7.4.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - loguru==0.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - narwhals==1.7.0
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.29.0
      - openai==1.44.1
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.4
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==5.28.1
      - psutil==6.0.0
      - pudb==2024.1.2
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyrr==0.10.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.8.1
      - rpds-py==0.20.0
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - streamlit==1.38.0
      - tenacity==8.5.0
      - test-tube==0.7.5
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tiktoken==0.7.0
      - timm==1.0.11
      - tokenizers==0.20.2
      - toml==0.10.2
      - tornado==6.4.1
      - tqdm==4.66.5
      - transformers==4.46.1
      - typeguard==4.3.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - urwid==2.6.15
      - urwid-readline==0.14
      - watchdog==4.0.2
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - yacs==0.1.8
      - yarl==1.11.1
      - zipp==3.20.1
