name: infinigen_sceneweaver
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - cuda-cudart=11.8.89=0
  - faiss-gpu=1.8.0=py3.10_hedc54c9_0_cuda11.4.4
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.11.3.6=0
  - libfaiss=1.8.0=h5aaf3ed_0_cuda11.4.4
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.21=h043d6bf_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py310h06a4308_0
  - pip=24.0=py310h06a4308_0
  - pybind11-abi=4=hd3eb1b0_1
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - attrs==24.2.0
      - black==24.8.0
      - bmipy==2.0.1
      - bpy==3.6.0
      - certifi==2024.7.4
      - cfgv==3.4.0
      - cftime==1.6.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - compress-json==1.1.1
      - compress-pickle==2.1.0
      - contourpy==1.2.1
      - coverage==7.6.1
      - cycler==0.12.1
      - cython==3.0.11
      - distlib==0.3.8
      - einops==0.8.0
      - execnet==2.1.1
      - filelock==3.15.4
      - flow-vis==0.1
      - fonttools==4.53.1
      - freetype-py==2.4.0
      - frozendict==2.4.4
      - fsspec==2024.10.0
      - ftfy==6.3.1
      - geomdl==5.3.1
      - gin-config==0.5.0
      - huggingface-hub==0.26.2
      - identify==2.6.0
      - idna==3.7
      - imageio==2.34.2
      - immutabledict==4.2.0
      - importlab==0.8.1
      - importlib-resources==6.4.0
      - infinigen==1.6.1
      - iniconfig==2.0.0
      - isort==5.13.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - landlab==2.8.0
      - lazy-loader==0.4
      - libcst==1.4.0
      - llvmlite==0.43.0
      - manifold3d==2.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - mdurl==0.1.2
      - msgspec==0.18.6
      - mypy-extensions==1.0.0
      - netcdf4==1.7.1.post1
      - networkx==3.1
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - numba==0.60.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - open-clip-torch==2.29.0
      - opencv-python==4.10.0.84
      - pandas==2.2.2
      - pathspec==0.12.1
      - patsy==0.5.6
      - pillow==10.4.0
      - platformdirs==4.2.2
      - pluggy==1.5.0
      - pre-commit==3.8.0
      - psutil==6.0.0
      - pycnite==2024.7.31
      - pydot==3.0.1
      - pyglet==1.5.29
      - pygments==2.18.0
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyrender==0.1.45
      - pyshp==2.3.1
      - pytest==8.3.2
      - pytest-cov==5.0.0
      - pytest-ordering==0.6
      - pytest-timeout==2.3.1
      - pytest-xdist==3.6.1
      - python-dateutil==2.9.0.post0
      - python-fcl==0.7.0.6
      - pytype==2024.4.11
      - pytz==2024.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.7.1
      - rich-click==1.8.3
      - rtree==1.3.0
      - ruff==0.5.6
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - sentence-transformers==3.2.1
      - shapely==2.0.5
      - six==1.16.0
      - statsmodels==0.14.2
      - submitit==1.5.1
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - timm==1.0.11
      - tokenizers==0.20.3
      - toml==0.10.2
      - tomli==2.0.1
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.66.5
      - transformers==4.46.2
      - trimesh==4.4.3
      - tzdata==2024.1
      - urllib3==2.2.2
      - virtualenv==20.26.3
      - wcwidth==0.2.13
      - xarray==2024.7.0
      - zstandard==0.23.0
prefix: /home/yandan/anaconda3/envs/infinigen_sceneweaver
